/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabajoed;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM124
 */
public class MenuUsuario extends javax.swing.JFrame {

    Administracion empresa=new Administracion();
    private Cliente clienteActivo;
        
    private DefaultTableModel modeloTablaCompras;
    
    public MenuUsuario() {
        initComponents();
        
        clienteActivo=empresa.devolverUsuario(Inicio.DNIActivo);
        
        lblUsuario.setText(clienteActivo.getNombre());
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnDesconectar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnVerCompras = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnCatalogo = new javax.swing.JButton();
        btnReparaciones = new javax.swing.JButton();
        pnlCompra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboxCantidadCPU = new javax.swing.JComboBox<>();
        lblPrecioCPU = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPrecioRAM = new javax.swing.JLabel();
        cboxCantidadRAM = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblPrecioMonitor = new javax.swing.JLabel();
        cboxCantidadMonitor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboxCantidadAcc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        btnConfirmarCompra = new javax.swing.JButton();
        lblTotalCPU = new javax.swing.JLabel();
        lblTotalRAM = new javax.swing.JLabel();
        lblTotalMonitor = new javax.swing.JLabel();
        lblTotalAcc = new javax.swing.JLabel();
        rbtnTarjeta = new javax.swing.JRadioButton();
        rbtnCuenta = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlPerfil = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNuevoNombre = new javax.swing.JTextField();
        btnConfirmarPerfil = new javax.swing.JButton();
        lblErrorPerfilNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNuevaDireccion = new javax.swing.JTextField();
        lblErrorDireccion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNuevoTelefono = new javax.swing.JTextField();
        lblErrorTelefono = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNuevaTarjeta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNuevaCuenta = new javax.swing.JTextField();
        lblErrorTarjeta = new javax.swing.JLabel();
        lblErrorCuenta = new javax.swing.JLabel();
        pnlVerCompras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnVerCompras.setText("Ver compras");
        btnVerCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerComprasActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUsuario)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDesconectar)
                            .addComponent(btnVerCompras))
                        .addGap(39, 39, 39))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPerfil)
                        .addComponent(btnMenu)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDesconectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(52, 52, 52))
        );

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlPrincipal.setLayout(new java.awt.CardLayout());

        btnCatalogo.setText("Ver Catálogo");
        btnCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoActionPerformed(evt);
            }
        });

        btnReparaciones.setText("Reparaciones");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnCatalogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btnReparaciones)
                .addGap(40, 40, 40))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReparaciones)
                    .addComponent(btnCatalogo))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlMenu, "card2");

        jLabel1.setText("CPU");

        cboxCantidadCPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cboxCantidadCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCantidadCPUActionPerformed(evt);
            }
        });

        lblPrecioCPU.setText("200 €/uni");

        jLabel2.setText("Memoria RAM");

        lblPrecioRAM.setText("60 €/uni");

        cboxCantidadRAM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cboxCantidadRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCantidadRAMActionPerformed(evt);
            }
        });

        jLabel4.setText("Monitor");

        lblPrecioMonitor.setText("80 €/uni");

        cboxCantidadMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cboxCantidadMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCantidadMonitorActionPerformed(evt);
            }
        });

        jLabel6.setText("Accesorios");

        jLabel3.setText("20 €/uni");

        cboxCantidadAcc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cboxCantidadAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCantidadAccActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio Total: ");

        lblPrecioTotal.setText("0 ");

        btnConfirmarCompra.setText("Comprar");
        btnConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCompraActionPerformed(evt);
            }
        });

        lblTotalCPU.setText("0 ");

        lblTotalRAM.setText("0 ");

        lblTotalMonitor.setText("0 ");

        lblTotalAcc.setText("0 ");

        buttonGroup1.add(rbtnTarjeta);
        rbtnTarjeta.setText("Tarjeta de Crédito");

        buttonGroup1.add(rbtnCuenta);
        rbtnCuenta.setText("Cuenta corriente");

        jLabel12.setText("Método de pago:");

        jCheckBox1.setText("Con envío");

        jLabel13.setText("€");

        jLabel14.setText("€");

        jLabel15.setText("€");

        jLabel16.setText("€");

        jLabel17.setText("€");

        javax.swing.GroupLayout pnlCompraLayout = new javax.swing.GroupLayout(pnlCompra);
        pnlCompra.setLayout(pnlCompraLayout);
        pnlCompraLayout.setHorizontalGroup(
            pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCompraLayout.createSequentialGroup()
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addGap(17, 348, Short.MAX_VALUE)
                        .addComponent(btnConfirmarCompra))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCompraLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCompraLayout.createSequentialGroup()
                                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecioCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrecioRAM)
                                    .addComponent(lblPrecioMonitor)
                                    .addComponent(jLabel3))
                                .addGap(66, 66, 66))
                            .addGroup(pnlCompraLayout.createSequentialGroup()
                                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(rbtnCuenta)
                                    .addComponent(rbtnTarjeta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCompraLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecioTotal))
                            .addGroup(pnlCompraLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCompraLayout.createSequentialGroup()
                                        .addComponent(cboxCantidadCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotalCPU))
                                    .addGroup(pnlCompraLayout.createSequentialGroup()
                                        .addComponent(cboxCantidadRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotalRAM))
                                    .addGroup(pnlCompraLayout.createSequentialGroup()
                                        .addComponent(cboxCantidadMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotalMonitor))
                                    .addGroup(pnlCompraLayout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(pnlCompraLayout.createSequentialGroup()
                                        .addComponent(cboxCantidadAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotalAcc)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlCompraLayout.setVerticalGroup(
            pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPrecioCPU)
                    .addComponent(cboxCantidadCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalCPU)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPrecioRAM)
                    .addComponent(cboxCantidadRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalRAM)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblPrecioMonitor)
                    .addComponent(cboxCantidadMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalMonitor)
                    .addComponent(jLabel15))
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)))
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxCantidadAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalAcc)
                            .addComponent(jLabel16))))
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnTarjeta))
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblPrecioTotal)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnCuenta)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnConfirmarCompra)
                .addGap(19, 19, 19))
        );

        pnlPrincipal.add(pnlCompra, "card3");

        jLabel7.setText("Nombre: ");

        btnConfirmarPerfil.setText("Confirmar");
        btnConfirmarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPerfilActionPerformed(evt);
            }
        });

        jLabel8.setText("Direccion:");

        jLabel9.setText("Teléfono: ");

        jLabel10.setText("Tarjeta: ");

        jLabel11.setText("Cuenta: ");

        javax.swing.GroupLayout pnlPerfilLayout = new javax.swing.GroupLayout(pnlPerfil);
        pnlPerfil.setLayout(pnlPerfilLayout);
        pnlPerfilLayout.setHorizontalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmarPerfil)
                .addGap(20, 20, 20))
            .addGroup(pnlPerfilLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlPerfilLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(21, 21, 21)
                            .addComponent(txtNuevaTarjeta))
                        .addGroup(pnlPerfilLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNuevoTelefono))
                        .addGroup(pnlPerfilLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNuevaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlPerfilLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(txtNuevoNombre))
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorPerfilNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlPerfilLayout.setVerticalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerfilLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorPerfilNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNuevaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNuevoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtNuevaTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnConfirmarPerfil)
                .addGap(19, 19, 19))
        );

        pnlPrincipal.add(pnlPerfil, "card4");

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REFERENCIA", "PRECIO TOTAL", "METODO DE PAGO"
            }
        ));
        jScrollPane1.setViewportView(tablaCompras);

        javax.swing.GroupLayout pnlVerComprasLayout = new javax.swing.GroupLayout(pnlVerCompras);
        pnlVerCompras.setLayout(pnlVerComprasLayout);
        pnlVerComprasLayout.setHorizontalGroup(
            pnlVerComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVerComprasLayout.setVerticalGroup(
            pnlVerComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPrincipal.add(pnlVerCompras, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * El botón desconectar cierra tu sesión y te devuelve a la 
     * ventana de inicio. 
     */
    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        
        dispose();
        Inicio in=new Inicio();
        in.setVisible(true);
        
    }//GEN-LAST:event_btnDesconectarActionPerformed
 /**
     * El botón catálogo te muestra el catálogo de compra.
     */
    private void btnCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoActionPerformed
        
        pnlMenu.setVisible(false);
        pnlCompra.setVisible(true);
        
    }//GEN-LAST:event_btnCatalogoActionPerformed
/**
     * Este método finaliza el programa.
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        
        System.exit(0);
        
    }//GEN-LAST:event_btnSalirActionPerformed
/**
     * Este método te permite entrar al perfil donde se puede cambiar tus datos personales
     * e introducir tu número de cuenta bancaria y tu número de tarjeta de crédito.
     */
    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        
        pnlVerCompras.setVisible(false);
        pnlCompra.setVisible(false);
        pnlMenu.setVisible(false);
        pnlPerfil.setVisible(true);
        
        txtNuevoNombre.setText(clienteActivo.getNombre());
        txtNuevaDireccion.setText(clienteActivo.getDireccion());
        txtNuevoTelefono.setText(clienteActivo.getTelefono());
        txtNuevaTarjeta.setText(clienteActivo.getTarjetaCredito());
        txtNuevaCuenta.setText(clienteActivo.getCuentaCorriente());
    }//GEN-LAST:event_btnPerfilActionPerformed
/**
     * Este método comprueba que los nuevos datos sean válidos si no es así te avisa del error. 
     */
    private void btnConfirmarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPerfilActionPerformed
        
        boolean valido=true;
        
        
        String nuevaTarjeta="Si sale esto está mal";
        String nuevaCuenta="Si sale esto está mal";
        
        if(!Validaciones.introducirNombre(txtNuevoNombre.getText())){        
            lblErrorPerfilNombre.setForeground(Color.red);
            lblErrorPerfilNombre.setText("Nombre Incorrecto");            
            valido=false;
        }else{
            lblErrorPerfilNombre.setText("");
        }
        
        if(!Validaciones.introducirDireccion(txtNuevaDireccion.getText())){
            lblErrorDireccion.setForeground(Color.red);
            lblErrorDireccion.setText("Dirección Incorrecta");
            valido=false;
        }else{
            lblErrorDireccion.setText("");
        }
        
        if(!Validaciones.introducirNumero(txtNuevoTelefono.getText())){
            lblErrorTelefono.setForeground(Color.red);
            lblErrorTelefono.setText("Telefono Incorrecto");
            valido=false;
        }else{
            lblErrorTelefono.setText("");
        }
        
        
        if(txtNuevaTarjeta.getText().equals("")){
            nuevaTarjeta=null;
        }else if(!Validaciones.introducirTarjeta(txtNuevaTarjeta.getText())){
            lblErrorTarjeta.setForeground(Color.red);
            lblErrorTarjeta.setText("Tarjeta Incorrecta");
            
            
            
            valido=false;
        }else{
            nuevaTarjeta=txtNuevaTarjeta.getText();
            lblErrorTarjeta.setText("");
        }
        
        if(txtNuevaCuenta.getText().equals("")){
            nuevaCuenta=null;
        }else if(!Validaciones.introducirCuenta(txtNuevaCuenta.getText())){
            lblErrorCuenta.setForeground(Color.red);
            lblErrorCuenta.setText("Cuenta Corriente Incorrecta");
            
            
            
            valido=false;
        }else{
            lblErrorCuenta.setText("");
            nuevaCuenta=txtNuevaCuenta.getText();
        }
        
        
        if(valido){
            empresa.cambiarNombreUsuario(txtNuevoNombre.getText(), clienteActivo.getNIF());
            empresa.cambiarDireccionUsuario(txtNuevaDireccion.getText(), clienteActivo.getNIF());
            empresa.cambiarTelefono(txtNuevoTelefono.getText(), clienteActivo.getNIF());
            empresa.cambiarTarjeta(nuevaTarjeta, clienteActivo.getNIF());
            empresa.cambiarCuenta(nuevaCuenta, clienteActivo.getNIF());
            clienteActivo.setNombre(txtNuevoNombre.getText());
            clienteActivo.setDireccion(txtNuevaDireccion.getText());
            clienteActivo.setTelefono(txtNuevoTelefono.getText());
            clienteActivo.setTarjetaCredito(nuevaTarjeta);
            clienteActivo.setCuentaCorriente(nuevaCuenta);
            lblUsuario.setText(clienteActivo.getNombre());
            
            
            empresa.guardarClientes(empresa);
            JOptionPane.showMessageDialog(null, "Perfil actualizado",
                        "Perfil actualizado", JOptionPane.INFORMATION_MESSAGE, null);
        }
        
    }//GEN-LAST:event_btnConfirmarPerfilActionPerformed
/**
     * Este método permite seleccionar una cantidad de unidads para comprar.
     */
    private void cboxCantidadCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCantidadCPUActionPerformed
        
        int cantidadCPU=0;
        int cantidadRAM=0;
        int cantidadMonitor=0;
        int cantidadAccesorios=0;
        
        cantidadCPU=Integer.parseInt(cboxCantidadCPU.getSelectedItem().toString());
        cantidadRAM=Integer.parseInt(cboxCantidadRAM.getSelectedItem().toString());
        cantidadMonitor=Integer.parseInt(cboxCantidadMonitor.getSelectedItem().toString());
        cantidadAccesorios=Integer.parseInt(cboxCantidadAcc.getSelectedItem().toString());
        
        int precioCPU=200;
        int precioRAM=60;
        int precioMonitor=80;
        int precioAccesorios=20;
        
        String totalCPU=String.valueOf(cantidadCPU*precioCPU);
        String totalRAM=String.valueOf(cantidadRAM*precioRAM);
        String totalMonitor=String.valueOf(cantidadMonitor*precioMonitor);
        String totalAcc=String.valueOf(cantidadAccesorios*precioAccesorios);
        String precioTotal=String.valueOf((cantidadCPU*precioCPU)+(cantidadRAM*precioRAM)
        + (cantidadMonitor*precioMonitor)+(cantidadAccesorios*precioAccesorios));
        
        lblTotalCPU.setText(totalCPU);
        lblTotalRAM.setText(totalRAM);
        lblTotalMonitor.setText(totalMonitor);
        lblTotalAcc.setText(totalAcc);
        
        lblPrecioTotal.setText(precioTotal);
    }//GEN-LAST:event_cboxCantidadCPUActionPerformed
/**
     * Este método permite seleccionar una cantidad de unidads para comprar.
     */
    private void cboxCantidadRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCantidadRAMActionPerformed
        int cantidadCPU=0;
        int cantidadRAM=0;
        int cantidadMonitor=0;
        int cantidadAccesorios=0;
        
        cantidadCPU=Integer.parseInt(cboxCantidadCPU.getSelectedItem().toString());
        cantidadRAM=Integer.parseInt(cboxCantidadRAM.getSelectedItem().toString());
        cantidadMonitor=Integer.parseInt(cboxCantidadMonitor.getSelectedItem().toString());
        cantidadAccesorios=Integer.parseInt(cboxCantidadAcc.getSelectedItem().toString());
        
        int precioCPU=200;
        int precioRAM=60;
        int precioMonitor=80;
        int precioAccesorios=20;
        
        String totalCPU=String.valueOf(cantidadCPU*precioCPU);
        String totalRAM=String.valueOf(cantidadRAM*precioRAM);
        String totalMonitor=String.valueOf(cantidadMonitor*precioMonitor);
        String totalAcc=String.valueOf(cantidadAccesorios*precioAccesorios);
        String precioTotal=String.valueOf((cantidadCPU*precioCPU)+(cantidadRAM*precioRAM)
        + (cantidadMonitor*precioMonitor)+(cantidadAccesorios*precioAccesorios));
        
        lblTotalCPU.setText(totalCPU);
        lblTotalRAM.setText(totalRAM);
        lblTotalMonitor.setText(totalMonitor);
        lblTotalAcc.setText(totalAcc);
        
        lblPrecioTotal.setText(precioTotal);
    }//GEN-LAST:event_cboxCantidadRAMActionPerformed
/**
     * Este método permite seleccionar una cantidad de unidads para comprar.
     */
    private void cboxCantidadMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCantidadMonitorActionPerformed
        // TODO add your handling code here:
        
        int cantidadCPU=0;
        int cantidadRAM=0;
        int cantidadMonitor=0;
        int cantidadAccesorios=0;
        
        cantidadCPU=Integer.parseInt(cboxCantidadCPU.getSelectedItem().toString());
        cantidadRAM=Integer.parseInt(cboxCantidadRAM.getSelectedItem().toString());
        cantidadMonitor=Integer.parseInt(cboxCantidadMonitor.getSelectedItem().toString());
        cantidadAccesorios=Integer.parseInt(cboxCantidadAcc.getSelectedItem().toString());
        
        int precioCPU=200;
        int precioRAM=60;
        int precioMonitor=80;
        int precioAccesorios=20;
        
        String totalCPU=String.valueOf(cantidadCPU*precioCPU);
        String totalRAM=String.valueOf(cantidadRAM*precioRAM);
        String totalMonitor=String.valueOf(cantidadMonitor*precioMonitor);
        String totalAcc=String.valueOf(cantidadAccesorios*precioAccesorios);
        String precioTotal=String.valueOf((cantidadCPU*precioCPU)+(cantidadRAM*precioRAM)
        + (cantidadMonitor*precioMonitor)+(cantidadAccesorios*precioAccesorios));
        
        lblTotalCPU.setText(totalCPU);
        lblTotalRAM.setText(totalRAM);
        lblTotalMonitor.setText(totalMonitor);
        lblTotalAcc.setText(totalAcc);
        
        lblPrecioTotal.setText(precioTotal);
    }//GEN-LAST:event_cboxCantidadMonitorActionPerformed
/**
     * Este método permite seleccionar una cantidad de unidads para comprar.
     */
    private void cboxCantidadAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCantidadAccActionPerformed
        // TODO add your handling code here:
        
        int cantidadCPU=0;
        int cantidadRAM=0;
        int cantidadMonitor=0;
        int cantidadAccesorios=0;
        
        cantidadCPU=Integer.parseInt(cboxCantidadCPU.getSelectedItem().toString());
        cantidadRAM=Integer.parseInt(cboxCantidadRAM.getSelectedItem().toString());
        cantidadMonitor=Integer.parseInt(cboxCantidadMonitor.getSelectedItem().toString());
        cantidadAccesorios=Integer.parseInt(cboxCantidadAcc.getSelectedItem().toString());
        
        int precioCPU=200;
        int precioRAM=60;
        int precioMonitor=80;
        int precioAccesorios=20;
        
        String totalCPU=String.valueOf(cantidadCPU*precioCPU);
        String totalRAM=String.valueOf(cantidadRAM*precioRAM);
        String totalMonitor=String.valueOf(cantidadMonitor*precioMonitor);
        String totalAcc=String.valueOf(cantidadAccesorios*precioAccesorios);
        String precioTotal=String.valueOf((cantidadCPU*precioCPU)+(cantidadRAM*precioRAM)
        + (cantidadMonitor*precioMonitor)+(cantidadAccesorios*precioAccesorios));
        
        lblTotalCPU.setText(totalCPU);
        lblTotalRAM.setText(totalRAM);
        lblTotalMonitor.setText(totalMonitor);
        lblTotalAcc.setText(totalAcc);
        
        lblPrecioTotal.setText(precioTotal);
    }//GEN-LAST:event_cboxCantidadAccActionPerformed
/**
     * Este método confirma tu compra, te la muestra por pantalla.
     */
    private void btnConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCompraActionPerformed
        // TODO add your handling code here:

        String detallesCompra = "";
        boolean valido = false;
        char metodo=' ';
        String referencia="";

        if (rbtnTarjeta.isSelected() || rbtnCuenta.isSelected()) {
            if (rbtnTarjeta.isSelected() && clienteActivo.getTarjetaCredito() != null) {

                detallesCompra = "Detalles de la compra: "
                        + "\nUsuario: "
                        + "\n\t " + clienteActivo.getNombre()
                        + "\nPrecio total: "
                        + "\n\t" + lblPrecioTotal.getText()+"€"
                        + "\nMétodo de pago: "
                        + "\n\tTarjeta de Crédito";
                
                referencia=clienteActivo.getId()+clienteActivo.getNombre().substring(0,3)+empresa.getNumeroCompras();
                empresa.setNumeroCompras(empresa.getNumeroCompras()+1);
                metodo='T';

                

                valido = true;

            } else if (rbtnCuenta.isSelected() && clienteActivo.getCuentaCorriente() != null) {
                
                referencia=clienteActivo.getId()+clienteActivo.getNombre().substring(0,3)+empresa.getNumeroCompras();
                empresa.setNumeroCompras(empresa.getNumeroCompras()+1);
                
                metodo='C';
                detallesCompra = "Detalles de la compra: "
                        + "\nUsuario: "
                        + "\n\t " + clienteActivo.getNombre()
                        + "\nPrecio total: "
                        + "\n\t" + lblPrecioTotal.getText()+"€"
                        + "\nMétodo de pago: "
                        + "\n\tCuenta Corriente.";
                
                

                valido = true;
            }

            if (!valido) {

                JOptionPane.showMessageDialog(null, "No se ha encontrado el método de pago"
                        + " en su perfil. Vaya a Perfil y añadalo.", "Error al procesar la compra.",
                        JOptionPane.ERROR_MESSAGE, null);
            } else {
                JOptionPane.showMessageDialog(null, detallesCompra, "Compra realizada.",
                        JOptionPane.PLAIN_MESSAGE, null);
                
                Compra compra=new Compra(referencia, Double.valueOf(lblPrecioTotal.getText()), metodo);
                empresa.añadirCompra(compra);
                empresa.guardarCompras(empresa);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un método de pago", "Error al procesar la compra.",
                    JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btnConfirmarCompraActionPerformed
/**
     * Este botón te permite acceder al panel verComprasr.
     */
    private void btnVerComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerComprasActionPerformed
        
        pnlMenu.setVisible(false);
        pnlPerfil.setVisible(false);
        pnlCompra.setVisible(false);
        pnlVerCompras.setVisible(true);
        
        
        
        String[]columnas={"REFERENCIA","PRECIO TOTAL","MÉTODO DE PAGO"};
        modeloTablaCompras=new DefaultTableModel(columnas, 0);
        tablaCompras.setModel(modeloTablaCompras);
        ArrayList<Compra> lista=empresa.getListadoCompras();
        
        
        
        if(lista!=null){
            for(Compra c:lista){
                
                if(c.getReferencia().substring(0,1).equals(String.valueOf(clienteActivo.getId()))){
                    modeloTablaCompras.addRow(new Object[]{c.getReferencia(), c.getPrecioTotal(), c.getMetodoPago()} );
                }
                
            }
        }
        
        
    }//GEN-LAST:event_btnVerComprasActionPerformed
/**
     * Este botón te devuelve al panel de menú.
     */
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        
        pnlVerCompras.setVisible(false);
        pnlCompra.setVisible(false);
        pnlMenu.setVisible(true);
        pnlPerfil.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnConfirmarCompra;
    private javax.swing.JButton btnConfirmarPerfil;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReparaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerCompras;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboxCantidadAcc;
    private javax.swing.JComboBox<String> cboxCantidadCPU;
    private javax.swing.JComboBox<String> cboxCantidadMonitor;
    private javax.swing.JComboBox<String> cboxCantidadRAM;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorCuenta;
    private javax.swing.JLabel lblErrorDireccion;
    private javax.swing.JLabel lblErrorPerfilNombre;
    private javax.swing.JLabel lblErrorTarjeta;
    private javax.swing.JLabel lblErrorTelefono;
    private javax.swing.JLabel lblPrecioCPU;
    private javax.swing.JLabel lblPrecioMonitor;
    private javax.swing.JLabel lblPrecioRAM;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblTotalAcc;
    private javax.swing.JLabel lblTotalCPU;
    private javax.swing.JLabel lblTotalMonitor;
    private javax.swing.JLabel lblTotalRAM;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlCompra;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPerfil;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlVerCompras;
    private javax.swing.JRadioButton rbtnCuenta;
    private javax.swing.JRadioButton rbtnTarjeta;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTextField txtNuevaCuenta;
    private javax.swing.JTextField txtNuevaDireccion;
    private javax.swing.JTextField txtNuevaTarjeta;
    private javax.swing.JTextField txtNuevoNombre;
    private javax.swing.JTextField txtNuevoTelefono;
    // End of variables declaration//GEN-END:variables

}
